export const NotRequired = { required: false }
export const Nullable = { nullable: true }
export const NullableNotRequired = { ...Nullable, ...NotRequired }

export const Integer = { type: "integer", format: "int32" }
export const IntegerNullable = { ...Integer, ...Nullable }
export const IntegerNotRequired = { ...Integer, ...NotRequired}
export const IntegerNullableNotRequired = { ...Integer, ...Nullable, ...NotRequired }
export const Integers = { type: "array", items: Integer }
export const IntegersNotRequired = { ...Integers, ...NotRequired }
export const Long = { type: "integer", format: "int64" }
export const LongNullable = { ...Long, ...Nullable }
export const Timestamp = { type: "integer", format: "int64" }
export const TimestampNullable = { ...Timestamp, ...Nullable }
export const Date = { type: "string", format: "date" }
export const DateNullable = { ...Date, ...Nullable }
export const DateNotRequired = { ...Date, ...NotRequired }
export const DateTime = { type: "string", format: "date-time" }
export const ID = { type: "string" }
export const FileObject = { type: "object", properties: { file: { type: "string", format: "binary" }}}
export const StringMap = { type: "object", additionalProperties: { type: "string" }}
export const StringMapNullable = { ...StringMap, nullable: true }
export const IntegerMap = { type: "object", additionalProperties: Integer }
export const DateMap = { type: "object", additionalProperties: Date }
export const DateNullableMap = { type: "object", additionalProperties: DateNullable, example: { 'id1': '2021-01-01T00:00:00.000Z', 'id2': null } }